Repository antonschulz/zero-city-application, pull requests merged in 2022-04, with the labels that each got.

#17 Exhibition Map with Colors
  lib/exhibition_map/map.dart
  lib/exhibition_map/map_provider.dart
  lib/startsida.dart
  lib/utils/Graphics.dart
  lib/zones/planning_lab/mission1c.dart
  lib/zones/power-plant/mission1a.dart
  lib/zones/the-park/omvandlaParkeringsplats.dart
Labels: feature

#16 Global State Management
  lib/main.dart
  lib/state/planning_lab_state.dart
  lib/state/the_park_state.dart
  lib/zones/planning_lab/mission1a.dart
  lib/zones/planning_lab/mission1b.dart
  lib/zones/planning_lab/mission1c.dart
  lib/zones/the-park/omvandlaParkeringsplats.dart
Labels: enhancement, feature

#21 The Main Street
  lib/exhibition_map/map.dart
  lib/main.dart
  lib/state/main_street_state.dart
  lib/zones/main_street/main_street1.dart
  lib/zones/main_street/main_street2.dart
  lib/zones/main_street/main_street3.dart
  lib/zones/main_street/main_street_intro.dart
Labels: enhancement, feature

#24 The city zone
  lib/exhibition_map/map.dart
  lib/main.dart
  lib/state/the_city_state.dart
  lib/zones/the_city/the_city1.dart
  lib/zones/the_city/the_city2.dart
  lib/zones/the_city/the_city_intro.dart
Labels: zone
