Repository antonschulz/zero-city-application, pull requests merged in 2022-03, with the labels that each got.

#7 Fix Main Branch
  lib/main.dart
  pubspec.lock
Labels: bug, help wanted

#9 Text styles
  lib/main.dart
  lib/startsida.dart
  lib/text_types/mission_body.dart
  lib/text_types/mission_title.dart
  lib/text_types/zone_body.dart
  lib/text_types/zone_title.dart
  lib/zones/zone1/zone1_mission1.dart
Labels: enhancement

#10 Planning lab first version
  lib/exhibition_map/map.dart
  lib/zones/planning_lab/mission1a.dart
  lib/zones/planning_lab/mission1b.dart
  lib/zones/planning_lab/mission1c.dart
Labels: zone
